


export const GET_FORM_DETAILS_REQUEST= "GET_FORM_DETAILS_REQUEST"
export const GET_FORM_DETAILS_SUCCESS= "GET_FORM_DETAILS_SUCCESS"
export const GET_FORM_DETAILS_FAILURE= "GET_FORM_DETAILS_FAILURE"



////Add data in the data base


export const ADD_FORM_DETAILS_REQUEST= "ADD_FORM_DETAILS_REQUEST"
export const ADD_FORM_DETAILS_SUCCESS= "ADD_FORM_DETAILS_SUCCESS"
export const ADD_FORM_DETAILS_FAILURE= "ADD_FORM_DETAILS_FAILURE"


/////Delete Form



export const DELETE_FORM_DETAILS_SUCCESS= "DELETE_FORM_DETAILS_SUCCESS"


////get single Form

export const EDIT_SINGLE_FORM= "EDIT_SINGLE_FORM"

//////edit single form
export const UPDATE_SINGLE_FORM= "UPDATE_SINGLE_FORM"